migrate.source.xls:
  type: migrate_source
  label: 'XLS'
  mapping:
    path:
      type: string
      label: 'Path to the source XLS file'
    header_row:
      type: integer
      label: 'Header row index'
    keys:
      type: sequence
      label: 'Column name(s) which represent the key uniquely identifying each record'
      sequence:
        type: string
        label: 'Key field'
    columns:
      type: sequence
      label: 'Mapping of the columns in source XLS file'
